### ISSUE TITLE
How can I get multiple attributes from multiple nodes?

### ISSUE THREAD

**Issue by shaperilio** [mavrosxristoforos/get-xml-info#23]
I'm trying to parse a JUnit XML file. It looks something like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="1" skipped="0" tests="2" time="1.738"
        timestamp="2024-01-26T15:50:11.666897" hostname="Jordan">
        <testcase classname="pkg.tests.test_timing" name="test_tictoc" time="1.501" />
        <testcase classname="pkg.tests.test_timing" name="test_fail" time="0.001">
            <failure message="AssertionError">def test_fail():
                &gt; raise AssertionError
                E AssertionError

                pkg\tests\test_timing.py:34: AssertionError</failure>
        </testcase>
        <testcase classname="pkg.tests.test_timing" name="test_fail_some_more" time="0.001">
            <failure message="AssertionError">def test_fail_some_more():
                &gt; raise AssertionError
                E AssertionError

                pkg\tests\test_timing.py:65: AssertionError</failure>
        </testcase>
    </testsuite>
</testsuites>
```

I'd like to extract the list of failed tests, i.e. I need to get an array of the combination of `@classname` and `@name`.

If I set, for example, `xpath: //failure/parent::testcase/@name`, I get 'test_fail' and 'test_fail_some_more'. If I have a single failure, `concat(//failure/parent::testcase/@classname, '.', //failure/parent::testcase/@name)` works. But with multiple failures, I need something like `//failure/parent::testcase/concat(@name, '.', @classname)`, and then your action throws a parse error:

```
XPath: //failure/parent::testcase/concat(@classname, '.', @name)
Zero Nodes Action: error
Namespaces: null
File was read successfully. Proceeding to parse DOM.
/home/runner/work/_actions/mavrosxristoforos/get-xml-info/1.2.1/dist/index.js:9512
                    throw new Error("XPath parse error");
                    ^

Error: XPath parse error
    at XPathParser.parse (/home/runner/work/_actions/mavrosxristoforos/get-xml-info/1.2.1/dist/index.js:9512:27)
    at new XPathExpression (/home/runner/work/_actions/mavrosxristoforos/get-xml-info/1.2.1/dist/index.js:126[19](https://github.com/taut-ai/taut/actions/runs/7675369004/job/20921497064#step:8:20):[24](https://github.com/taut-ai/taut/actions/runs/7675369004/job/20921497064#step:8:25))
    at Object.exports.selectWithResolver (/home/runner/work/_actions/mavrosxristoforos/get-xml-info/1.2.1/dist/index.js:13096:[26](https://github.com/taut-ai/taut/actions/runs/7675369004/job/20921497064#step:8:27))
    at exports.select (/home/runner/work/_actions/mavrosxristoforos/get-xml-info/1.2.1/dist/index.js:1[30](https://github.com/taut-ai/taut/actions/runs/7675369004/job/20921497064#step:8:31)79:24)
    at read (/home/runner/work/_actions/mavrosxristoforos/get-xml-info/1.2.1/dist/index.js:13335:19)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by mavrosxristoforos** [comment]
Any idea @m-ringler?

**Comment by m-ringler** [comment]
When you want to process elements of sequences with XPath, you need to use `for $a in //foo return do-something-with($a)`. Note that this is not what xpath is originally made for. Have a look at full-fledged XSLT or XQuery.

**Comment by m-ringler** [comment]
Powershell also has very nice XML processing built in. So you might want to consider replacing the custom action with a short inline powershell script.
